### ISSUE TITLE
NanoDump into other directory

### ISSUE THREAD

**Issue by Xitro01** [S3cur3Th1sSh1t/PowerSharpPack#10]
Hi,

NanoDump seems nice and the seperate script doesn't seem to be detected, while the whole pack is.
The only problem is that C:\Windows\temp is not readable/writeable for me, while C:\Windows\tasks is.

Is it possible to change the default folder or be able to give a parameter to define where you want to dump the file?
It seems double b64 encoded, and is therefore probably going to be a big mess (and probably not working) if I change it myself.

Thanks in advance!

**Comment by S3cur3Th1sSh1t** [comment]
The path is hardcoded into nanodump so you can only change it by compiling and embedding nanodump yourself.
