### ISSUE TITLE
Pass arguments directly to assembly

### ISSUE THREAD

**Issue by AdrianVollmer** [S3cur3Th1sSh1t/PowerSharpPack#4]
First of all, great idea for a git repo. Works well with [my tool](https://github.com/AdrianVollmer/PowerHub) ;). Thanks!

Second, I was trying to fix a bug in Invoke-Certify. You pass arguments like this:

``` 
   [C3rt1fy.Program]::main($Command.Split(" "))
```

So all arguments are passed as a string, the string is split at the spaces, and the segments are passed as individual arguments to the assembly. If one of the parameters (in this case the CA or the name of the template) contains a space, you're screwed because even when using quotes the string will be split at the wrong position.

I propose deleting the parameter Cmdlet binding at the beginning of the function and replacing the line above with this:

```
    [C3rt1fy.Program]::main([string[]]$args)
```

This should keep arguments with spaces surrounded by quotes intact.

I was about to submit a PR, but I see that it is done this way in all files. So before I do anything, let me know what you think.

**Comment by S3cur3Th1sSh1t** [comment]
Works well, good workaround, thanks!

Done with https://github.com/S3cur3Th1sSh1t/PowerSharpPack/commit/334b20115b7c6e492feea272219271147716eafa
