### ISSUE TITLE
SharpSpray issue

### ISSUE THREAD

**Issue by IAMinZoho** [S3cur3Th1sSh1t/PowerSharpPack#7]
I tried this command to simulate a password spraying attack using a specific password: user@123

PowerSharpPack` -SharpSpray -Command "--Passwords user@123 --Sleep 15"

After some time the PS session crashes after this mesage:
![11111](https://user-images.githubusercontent.com/84743508/178475059-5d9f867f-0abd-4f6d-bd09-858f13e356c3.JPG)

Please advise!

**Comment by S3cur3Th1sSh1t** [comment]
In the Screenshot, `SharpSniper` was executed and not `SharpSpray`.

Just import `SharpSpray` from here directly: 
* https://github.com/S3cur3Th1sSh1t/PowerSharpPack/blob/master/PowerSharpBinaries/Invoke-SharpSpray.ps1

And use it with `Invoke-SharpSpray -Command "xxx"`
